'use client';

import { useEffect, useState } from 'react';
import { AppMobileNavigation } from '@/components/AppMobileNavigation';
import { supabase } from '@/lib/supabase';
import { deriveAppViews, type PersonalAppView } from '@/lib/authz.js';
import { deriveFeatureCapabilities, normalizeFeatureRows } from '@/lib/feature-permissions.js';
import { useConfirmDialog } from '@/components/ConfirmDialogProvider';

type Record = { id:string; recorded_at:string; weight_kg:number|null; body_fat_percentage:number|null; systolic:number|null; diastolic:number|null; pulse:number|null };
const blank = () => ({ recorded_at:new Date().toISOString().slice(0,16), weight_kg:'', body_fat_percentage:'', systolic:'', diastolic:'', pulse:'' });
export default function HealthPage(){ const confirm=useConfirmDialog(); const [rows,setRows]=useState<Record[]>([]); const [form,setForm]=useState(blank); const [views,setViews]=useState<PersonalAppView[]>([]); const [editing,setEditing]=useState<string|null>(null); const [error,setError]=useState('');
 useEffect(()=>{ void (async()=>{ const {data:{session}}=await supabase.auth.getSession(); if(!session)return; const features=await supabase.rpc('get_my_features'); const caps=deriveFeatureCapabilities(features.error?[]:normalizeFeatureRows(features.data)); if(!caps.canTrackHealth)return; setViews(deriveAppViews(['patient','health'])); const data=await supabase.from('health_records').select('*').order('recorded_at',{ascending:false}); setRows((data.data??[]) as Record[]); })()},[]);
 async function save(e:React.FormEvent){e.preventDefault(); const value=(x:string)=>x===''?null:Number(x); const payload={recorded_at:new Date(form.recorded_at).toISOString(),weight_kg:value(form.weight_kg),body_fat_percentage:value(form.body_fat_percentage),systolic:value(form.systolic),diastolic:value(form.diastolic),pulse:value(form.pulse)}; if(Object.values(payload).slice(1).every(x=>x===null)){setError('Indica al menos un dato.');return;} const q=editing?supabase.from('health_records').update(payload).eq('id',editing):supabase.from('health_records').insert(payload); const result=await q.select().single(); if(result.error){setError('No se pudo guardar.');return;} setRows(v=>editing?v.map(x=>x.id===editing?result.data as Record:x):[result.data as Record,...v]);setForm(blank());setEditing(null);}
 async function remove(id:string){if(!await confirm({title:'Eliminar registro',message:'¿Eliminar este registro de salud?',confirmLabel:'Eliminar'}))return;const result=await supabase.from('health_records').delete().eq('id',id);if(result.error){setError('No se pudo eliminar.');return;}setRows(v=>v.filter(x=>x.id!==id));if(editing===id){setEditing(null);setForm(blank());}}
 return <main className="theme-page mx-auto min-h-screen max-w-md p-5 pb-28"><h1 className="mb-4 text-center font-bold">Salud</h1><form onSubmit={save} className="space-y-4 rounded-3xl bg-white p-4 shadow-sm"><label>Fecha y hora<input type="datetime-local" value={form.recorded_at} onChange={e=>setForm({...form,recorded_at:e.target.value})} className="w-full"/></label><section><h2 className="font-bold">Composición corporal</h2><input placeholder="Peso (kg)" type="number" value={form.weight_kg} onChange={e=>setForm({...form,weight_kg:e.target.value})}/><input placeholder="% de grasa" type="number" value={form.body_fat_percentage} onChange={e=>setForm({...form,body_fat_percentage:e.target.value})}/></section><section><h2 className="font-bold">Tensión arterial</h2><input placeholder="Sistólica" type="number" value={form.systolic} onChange={e=>setForm({...form,systolic:e.target.value})}/><input placeholder="Diastólica" type="number" value={form.diastolic} onChange={e=>setForm({...form,diastolic:e.target.value})}/><input placeholder="Pulso" type="number" value={form.pulse} onChange={e=>setForm({...form,pulse:e.target.value})}/></section>{error&&<p role="alert">{error}</p>}<button className="min-h-14 w-full rounded-2xl bg-slate-800 text-white">Guardar</button>{editing&&<button type="button" onClick={()=>void remove(editing)} className="min-h-12 w-full text-rose-600">Eliminar registro</button>}</form><div className="mt-4 space-y-2">{rows.map(r=><button key={r.id} onClick={()=>{setEditing(r.id);setForm({recorded_at:r.recorded_at.slice(0,16),weight_kg:String(r.weight_kg??''),body_fat_percentage:String(r.body_fat_percentage??''),systolic:String(r.systolic??''),diastolic:String(r.diastolic??''),pulse:String(r.pulse??'')})}} className="w-full rounded-2xl bg-white p-4 text-left">{r.weight_kg&&`${r.weight_kg} kg `}{r.body_fat_percentage&&`${r.body_fat_percentage}% `}{r.systolic&&`${r.systolic}/${r.diastolic} · ${r.pulse} ppm`}</button>)}</div><AppMobileNavigation current="health" resolvedViews={views}/></main> }
