'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronLeft, ChevronRight, Dumbbell, Plus } from 'lucide-react';
import { buildWorkoutExerciseCards, validateWorkoutSet } from '@/lib/gym-workouts.js';
import { deriveFeatureCapabilities, normalizeFeatureRows } from '@/lib/feature-permissions.js';
import { madridDateString } from '@/lib/historical-date.js';
import { supabase } from '@/lib/supabase';
type Membership={id:string;group_id:string}; type Exercise={code:string;name:string}; type Daily={id:string;exercise_code:string;exercise_name_snapshot:string}; type Set={id:string;exercise_code:string;weight_kg:number;reps:number;created_at:string}; type RoleRow={role_code:string};
const shift=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
export default function TrainingPage(){
 const router=useRouter(),today=madridDateString(); const [date,setDate]=useState(today),[member,setMember]=useState<Membership|null>(null),[user,setUser]=useState(''),[catalog,setCatalog]=useState<Exercise[]>([]),[daily,setDaily]=useState<Daily[]>([]),[sets,setSets]=useState<Set[]>([]),[pick,setPick]=useState(false),[active,setActive]=useState<{exerciseCode:string;name:string}|null>(null),[kg,setKg]=useState(''),[reps,setReps]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false); const historical=date<today;
 useEffect(()=>{const alive=true;void(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/');return}const m=await supabase.from('group_memberships').select('id, group_id').eq('user_id',session.user.id).eq('status','active').maybeSingle();const membership=m.data as Membership|null;if(!membership){router.replace('/');return}const [roles,features]=await Promise.all([supabase.from('user_roles').select('role_code').eq('membership_id',membership.id),supabase.rpc('get_my_features')]);const allowed=(roles.data??[]).some((r)=>((r as RoleRow).role_code==='gym_patient'))&&deriveFeatureCapabilities(features.error?[]:normalizeFeatureRows(features.data)).canTrackGymWorkouts;if(!allowed){router.replace('/');return}const [c,d,s]=await Promise.all([supabase.from('gym_exercises').select('code, name').order('name'),supabase.from('gym_workout_exercises').select('id, exercise_code, exercise_name_snapshot').eq('user_id',session.user.id).eq('workout_date',date),supabase.from('gym_workout_sets').select('id, exercise_code, weight_kg, reps, created_at').eq('user_id',session.user.id).eq('workout_date',date).order('created_at')]);if(!alive)return;setMember(membership);setUser(session.user.id);setCatalog((c.data??[])as Exercise[]);setDaily((d.data??[])as Daily[]);setSets((s.data??[])as Set[]);if(c.error||d.error||s.error)setError('No se pudo cargar el entrenamiento.');setLoading(false)})()},[date,router]);
 const cards=useMemo(()=>buildWorkoutExerciseCards(daily,sets),[daily,sets]);const available=catalog.filter(x=>!daily.some(d=>d.exercise_code===x.code));
 async function addExercise(x:Exercise){if(!member)return;setSaving(true);const r=await supabase.from('gym_workout_exercises').insert({user_id:user,group_id:member.group_id,exercise_code:x.code,workout_date:date}).select('id, exercise_code, exercise_name_snapshot').single();if(r.error||!r.data)setError('No se pudo añadir el ejercicio.');else{setDaily(v=>[...v,r.data as Daily]);setPick(false)}setSaving(false)}
 async function addSet(e:React.FormEvent){e.preventDefault();if(!member||!active)return;try{const v=validateWorkoutSet({weightKg:Number(kg),reps:Number(reps)});setSaving(true);const r=await supabase.from('gym_workout_sets').insert({user_id:user,group_id:member.group_id,exercise_code:active.exerciseCode,exercise_name_snapshot:active.name,workout_date:date,weight_kg:v.weightKg,reps:v.reps}).select('id, exercise_code, weight_kg, reps, created_at').single();if(r.error||!r.data)setError('No se pudo guardar la serie.');else{setSets(s=>[...s,r.data as Set]);setActive(null);setKg('');setReps('')}}catch(e){setError(e instanceof Error?e.message:'Revisa la serie.')}finally{setSaving(false)}}
 if(loading)return <main className="theme-page min-h-screen p-6">Cargando entrenamiento…</main>;return <main className="theme-page min-h-screen pb-24 p-5"><header className="flex items-center justify-between"><button className="min-h-12 min-w-12" disabled={date<=today} onClick={()=>setDate(shift(date,-1))}><ChevronLeft/></button><h1 className="font-bold">Entrenamiento</h1><button className="min-h-12 min-w-12" onClick={()=>setDate(shift(date,1))}><ChevronRight/></button></header><p className="mb-4 text-center text-sm">{date}</p>{error&&<p role="alert">{error}</p>}{historical&&<p>El histórico es de solo lectura.</p>}{cards.map(c=><article key={c.id} className="mb-4 rounded-3xl bg-white p-5"><h2 className="border-b pb-3 font-bold">{c.name}</h2>{c.sets.map(s=><p key={s.id} className="flex justify-between py-3"><b>{s.weightKg} kg</b><span>{s.reps} reps</span></p>)}{!historical&&<button className="min-h-12 w-full rounded-2xl bg-rose-50" onClick={()=>setActive(c)}>Añadir serie</button>}</article>)}{!historical&&<button className="min-h-12 w-full rounded-2xl bg-slate-800 text-white" onClick={()=>setPick(true)}><Plus className="inline"/> Añadir ejercicio</button>}{pick&&<section className="fixed inset-x-0 bottom-0 bg-white p-5">{available.map(x=><button key={x.code} disabled={saving} className="min-h-12 w-full text-left" onClick={()=>void addExercise(x)}>{x.name}</button>)}</section>}{active&&<form onSubmit={addSet} className="fixed inset-x-0 bottom-0 bg-white p-5"><h2>{active.name}</h2><input aria-label="Peso (kg)" className="min-h-12" type="number" required value={kg} onChange={e=>setKg(e.target.value)}/><input aria-label="Repeticiones" className="min-h-12" type="number" required value={reps} onChange={e=>setReps(e.target.value)}/><button disabled={saving} className="min-h-12">Guardar serie</button></form>}<nav className="fixed bottom-0 inset-x-0 flex justify-around bg-white"><button className="min-h-12" onClick={()=>router.push('/')}>Plan diario</button><span className="min-h-12"><Dumbbell/> Entrenamiento</span></nav></main>
}
